
[app]
name          = "api"
project       = "confuse"
env           = "prod"
debug         = false
http_code     = "json"
tcp_code      = "protobuf"

[server]
bind_interface = ""

[server.http]
host           = "0.0.0.0"
port           = 15081
charset        = "UTF-8"
gzip           = true
pprof          = true

[jwt]
private_key    = "MFkwEwYHKoZIzj0C"
public_key     = ""
sign_type      = "HS"
sign_method    = "HS256"
expire_time    = 3